### ISSUE TITLE
Improve elasticsearch query options

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/argo#117]
## Describe the solution you'd like
1. Default search operator should be boolean AND
2. Enable query for a partial phrase using quotation marks
3. Enable boolean queries

## Additional context
Usability testing of [dimes](https://github.com/RockefellerArchiveCenter/dimes) frontend UI indicated the use of these search options would improve the user experience.

**Comment by helrond** [comment]
I've implemented a custom search backend, which combines a nested filter with a query: 3418dea240585b6d9019c45fcfea73e3a725d42e
And I've changed the query type to simple query string: 0250353559cdc06a5ee1cdbe3298d989a3ac12f4
